BREAKING CHANGE: removed exceptions made to indent
moxystudio/eslint-config-moxy pull request #83
Opened 2020-01-08 16:48 UTC by ritazoliveira

Removed the `SwitchCase` and `MemberExpression` indent rule exceptions .

2020-01-08 21:45 UTC, acostalima requested changes
We should add a few more samples to demonstrate how function calls can be chained without errors.

2020-01-09 12:23 UTC, acostalima approved these changes
LGTM! 👍

2020-01-09 12:24 UTC, acostalima commented
We should squash into a single commit and [add "BREAKING CHANGE" to the commit message body](https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-description-and-breaking-change-footer)!

2020-01-09 12:27 UTC, satazor commented on test/__snapshots__/index.spec.js.snap
> +  Object {
This seems to be a rule related to `block-spacing` and not indent. Check `style.js#18`

2020-01-09 12:27 UTC, satazor commented on test/__snapshots__/index.spec.js.snap
> +  Object {
Same.

2020-01-09 15:08 UTC, satazor approved these changes

2020-01-09 15:13 UTC, merged