feat: new single eslint-config-babel
moxystudio/eslint-config-moxy pull request #89
Opened 2020-03-18 14:55 UTC by satazor

BREAKING CHANGE: removed the previous three base packages in favor of just one

2020-03-18 16:27 UTC, acostalima requested changes
Awesome job! 👏 ❤️

2020-03-18 16:27 UTC, acostalima commented on packages/eslint-config-react/README.md
> +        "`@moxy/eslint-config-base/esm",
```suggestion
        "@moxy/eslint-config-base/esm",
```

2020-03-18 16:28 UTC, acostalima commented
Are we still using the `.spec.js` nomenclature for test files?

2020-03-18 16:42 UTC, satazor commented
@acostalima currently we support both. I can change the regexp to  only `test.js` as we are only using that in our projects.

2020-03-18 17:32 UTC, satazor commented
@acostalima removed `.spec.js`

2020-03-19 08:08 UTC, satazor commented on README.md
> +There are a few available **enhancer** packages, which are intended to be used in conjunction with the **base** configuration:
```suggestion
There are several **enhancer** packages, which are intended to be used in conjunction with the **base** configuration:
```

2020-03-19 08:11 UTC, satazor commented on packages/eslint-config-babel/README.md
> +ℹ️ Note that by setting `root` to true, we ensure that no ancestor configuration is used which also improves `ESLint` performance because no more file lookups need to be done.
```suggestion
```

2020-03-19 08:11 UTC, satazor commented on packages/eslint-config-babel/README.md
> +
```suggestion
```

2020-03-19 08:14 UTC, satazor commented on packages/eslint-config-base/README.md
> +- Example of `.eslintrc.json` for isomorphic projects that use ECMAScript modules:
```suggestion
- Example of `.eslintrc.json` for isomorphic / universal projects that use ECMAScript modules:
```

2020-03-19 08:17 UTC, satazor commented on README.md
> +  ℹ️ If your project is Isomorphic / Universal, you may want to enable the `node` environment as well.
```suggestion
  ℹ️ If your project is isomorphic / universal, you may want to enable the `node` environment as well.
```

2020-03-19 09:51 UTC, ruipneves approved these changes
LGTM 👍

2020-03-19 12:04 UTC, acostalima approved these changes

2020-03-19 15:30 UTC, dominguesgm approved these changes
LGTM 👍

2020-03-19 18:45 UTC, merged